# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ kj16-cb4 ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 16 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Print tool versions
        run: |
          java -version
          ./mvnw -B --version
          ant -version

      - name: Compile code
        run: ./mvnw -B -DskipTests package --file pom.xml

      - name: Run Tests
        # Tests in module ajde call Swing/AWT classes. Without frame buffer they throw
        # HeadlessException: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./mvnw -B -Daspectj.tests.verbose=false verify --file pom.xml
